---
name: cmpsc-100-fall-2018-lab1
break: true
indent: 4
---
src/main:
    java:
        labtwo/TipCalculator.java:
            --single 11 --language Java
            --multi 2 --language Java
            --fragment "println(" --count 9
            --fragment "new Date(" --count 1
            --fragment "$" --count 4
writing/reflection.md:
    --paragraphs 1 --exact
    --words 200
--commits 3
--command "gradle -q --console plain run" --executes
--command "gradle -q --console plain run" --count 10 --exact
